songs = [
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-carolina',
        "title": 'Carolina',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-estresse',
        "title": 'Estresse',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-on',
        "title": 'on',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-disco-platina',
        "title": 'Disco de Platina',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-herança',
        "title": 'Herança',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-numero-sorte',
        "title": 'Número da Sorte',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-passado-do-vilao',
        "title": 'Passado de um vilão',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-tempo-do-ouro',
        "title": 'Tempo do Ouro',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-ultima-vez',
        "title": 'Ultima vez',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,ANEZZI,KLISMAN-party',
        "title": 'Party',
        "artists": ['Alee', 'Klisman', 'Anezzi'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,BRANDAO85-segredo',
        "title": 'Segredo',
        "artists": ['Alee', 'Brandão 85'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,KLISMAN-alpinista',
        "title": 'Alpinista Social',
        "artists": ['Alee', 'Klisman'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,LZ-DAS-SETE-intro-malandragem',
        "title": 'Intro Malandragem',
        "artists": ['Alee', 'Lz Das Sete'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,SENNDY-amor-odio',
        "title": 'Amor e Ódio',
        "artists": ['Alee', 'Senndy'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-777-666',
        'title': "777-666",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-Antes',
        'title': "Antes",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-Cogulândia',
        'title': "Cogulândia",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-ÉSal',
        'title': "É Sal",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-GorillaRoxo',
        'title': "Gorilla Roxo",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-MDT',
        'title': "Máquina do Tempo",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-VemChapar',
        'title': "Vem Chapar",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
]


