songs = [
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-carolina',
        "title": 'Carolina',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-estresse',
        "title": 'Estresse',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-on',
        "title": 'on',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-disco-platina',
        "title": 'Disco de Platina',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-herança',
        "title": 'Herança',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-numero-sorte',
        "title": 'Número da Sorte',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-passado-do-vilao',
        "title": 'Passado de um vilão',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-tempo-do-ouro',
        "title": 'Tempo do Ouro',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE-ultima-vez',
        "title": 'Ultima vez',
        "artists": ['Alee'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,ANEZZI,KLISMAN-party',
        "title": 'Party',
        "artists": ['Alee', 'Klisman', 'Anezzi'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,BRANDAO85-segredo',
        "title": 'Segredo',
        "artists": ['Alee', 'Brandão 85'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,KLISMAN-alpinista',
        "title": 'Alpinista Social',
        "artists": ['Alee', 'Klisman'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,LZ-DAS-SETE-intro-malandragem',
        "title": 'Intro Malandragem',
        "artists": ['Alee', 'Lz Das Sete'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": "Trap",
        "cover": "ALEE-caos",
        "player": 'ALEE,SENNDY-amor-odio',
        "title": 'Amor e Ódio',
        "artists": ['Alee', 'Senndy'],
        "lyrics": None,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-777-666',
        'title': "777-666",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-Antes',
        'title': "Antes",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-Cogulândia',
        'title': "Cogulândia",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-ÉSal',
        'title': "É Sal",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-GorillaRoxo',
        'title': "Gorilla Roxo",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-MDT',
        'title': "Máquina do Tempo",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": 'Trap',
        "cover": 'MATUE-mdt',
        "player": 'Matuê-VemChapar',
        'title': "Vem Chapar",
        "artists": ['Matuê'],
        "lyrics": None,
        "light_color": '#000000',
        "dark_color": '#6B23FF',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-teatro-dos-vampiros',
        "title": 'Teatro dos Vampiros',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-pais-e-filhos',
        "title": 'Pais e Filhos',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-metal-contra-nuvens',
        "title": 'Metal Contra as Nuvens',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-mais-do-mesmo',
        "title": 'Mais do Mesmo',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-indios',
        "title": 'Índios',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-ha-tempos',
        "title": 'Há Tempos',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-faroeste-caboclo',
        "title": 'Faroeste Caboclo',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-eu-sei',
        "title": 'Eu Sei',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-baader-meinhof-blues',
        "title": 'Baader Meinhof Blues',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-serenissima',
        "title": 'Sereníssima',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-hoje-a-noite-nao-tem-luar',
        "title": 'Hoje à Noite Não Tem Luar',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "MPB",
        "cover": "LEGIAO-acústico",
        "player": 'LEGIAO-last-time-i-saw-richard',
        "title": 'Last Time I Saw Richard',
        "artists": ['Legião Urbana'],
        "lyrics": None,
        "light_color": '#0a083b',
        "dark_color": '#020113',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-seaside-rendzveus',
        "title": 'Seaside Rendezvous',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-sweety-lady',
        "title": 'Sweety Lady',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-youre-my-best-friend',
        "title": "You're My Best Friend",
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-prophet-song',
        "title": 'Prophet Song',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-love-of-my-life',
        "title": 'Love of My Life',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-lazing-on-sunday',
        "title": 'Lazing on a Sunday Afternoon',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-good-company',
        "title": 'Good Company',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-god-save-queen',
        "title": 'God Save the Queen',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-bohemian',
        "title": 'Bohemian Rhapsody',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-39',
        "title": "39",
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-death-on-two-legs',
        "title": 'Death on Two Legs',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    },
    {
        "genre": "Rock",
        "cover": "QUEEN-album",
        "player": 'QUEEN-love-with-my-car',
        "title": 'I’m in Love with My Car',
        "artists": ['Queen'],
        "lyrics": None,
        "light_color": '#afa0ae',
        "dark_color": '#943284',
    }
]
