users = [
    {
        "email": 'luansilva250807@gmail.com',
        "password": 'luan2508',
        "is_superuser": True,
        "is_staff": True,
        "is_active": True,
        "is_artist": False,	 
    },
    {
        "email": 'ALEE@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#67562e',
        "dark_color": '#4a3106',
        "perfil": 'ALEE-perfil',
        "background": 'ALEE-caos',
        "description": "O trapper ALEE nasceu e cresceu na Bahia, um estado que influencia profundamente sua música e estética, como é evidente em faixas como 'Sem Parar' e 'Banco de Couro'. Ele começou sua carreira no cenário musical trabalhando com a Hash Produções, inicialmente explorando o R&B antes de migrar para o trap, estilo que se tornou seu principal foco e identidade artística. Seu primeiro grande sucesso no trap foi a música 'Banco de Couro', que conta com a participação de Jovem Dex e rapidamente se tornou popular entre os fãs, destacando-se pela fusão inovadora de vocais e ad-libs modernos. Essa faixa consolidou ALEE como um dos talentos em ascensão no cenário do trap brasileiro."
    },
    {
        "email": 'ANEZZI@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#0d70b3',
        "dark_color": '#06374a',
        "perfil": 'ANEZZI-perfil',
        "background": 'ANEZZI-background',
        "description": "ANEZZi, nascido Thiago Silva Anesi Aragão, é um trapper carioca originário da Zona Oeste do Rio de Janeiro, criado no Jardim Paraíso, em Nova Iguaçu. Sua jornada começou na música com influências do street dance, no qual atuou por quatro anos antes de migrar para o universo musical. Sua carreira ganhou impulso em 2014, quando estabeleceu parcerias com produtores como Dallass, e mais tarde foi descoberto por Filipe Ret na TuduBom Records. Entre seus principais sucessos estão 'Bolo de Notas', que destaca sua versatilidade, e as faixas de R&B como 'Perdido' e 'Calor', que apresentam um lado introspectivo de seu repertório."
    },
    {
        "email": 'BRANDAO@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#0f956e',
        "dark_color": '#0d6a41',
        "perfil": 'BRANDAO-perfil',
        "background": 'BRANDAO-background',
        "description": "BRANDAO85 é um dos principais nomes emergentes do trap brasileiro, conhecido por sua musicalidade autêntica e presença marcante. Natural do Brasil, Brandão começou sua trajetória artística como cantor, compositor e produtor musical. Seu trabalho mais notável é o EP 'ZOO', que apresenta uma combinação única de sonoridades inspiradas em animais, demonstrando sua habilidade criativa e técnica. Além disso, Brandão85 é integrante da renomada gravadora 30PRAUM, anunciada por Matuê, consolidando sua posição no cenário do trap nacional. Entre suas faixas de maior destaque estão 'Orangotango' e 'Coruja', nas quais ele assinou a produção musical. O trapper continua a ganhar atenção e prestígio com lançamentos impactantes e shows memoráveis."
    },
    {
        "email": 'LZ-DAS-SETE@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#c8c8c8',
        "dark_color": '#6e6e6e',
        "perfil": 'LZ-DAS-SETE-perfil',
        "background": 'LZ-DAS-SETE-background',
        "description": ""
    },
    {
        "email": 'SENNDY@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#c8c8c8',
        "dark_color": '#6e6e6e',
        "perfil": 'SENNDY-perfil',
        "background": 'SENNDY-background',
        "description": ""
    },
    {
        "email": 'KLISMAN@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#950f4b',
        "dark_color": '#5a0d6a',
        "perfil": 'KLISMAN-perfil',
        "background": 'KLISMAN-background',
        "description": "Klisman, um trapper baiano nascido e criado no Centro Histórico de Salvador, é um artista profundamente influenciado pela rica diversidade musical da cidade. Desde cedo, acompanhava seu pai, um renomado percussionista de bandas icônicas do Pagode Baiano e Axé, como Olodum e É o Tchan, o que moldou sua identidade artística. Ele ganhou destaque no cenário nacional com sua coautoria no hit 'Dentro de Você', interpretado por Filipe Ret e Kevin o Chris. Além disso, Klisman lançou músicas como 'Oh Mãe', 'Ainda Penso em Você' (em colaboração com Anezzi) e 'NEUROSES' (com o rapper Alee). Recentemente, ele lançou o EP 'KD O CHTC?', que já ultrapassou um milhão de streams, consolidando seu lugar na cena do trap brasileiro."
    },
    {
        "email": 'LEGIAO@gmail.com',
        "password": 'alee1234',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,
        "light_color": '#daa545',
        "dark_color": '#524627',
        "perfil": 'LEGIAO-perfil',
        "background": 'LEGIAO-background',
        "description": "A Legião Urbana foi formada em 1982, em Brasília, liderada por Renato Russo, com Marcelo Bonfá na bateria. Inicialmente, a banda contou com Eduardo Paraná (guitarra) e Paulo Paulista (teclados), mas logo a formação foi consolidada com Dado Villa-Lobos na guitarra. Com letras marcantes e sonoridade única, se tornou um dos maiores ícones do rock nacional. Seu álbum de estreia trouxe o primeiro grande sucesso, 'Será', seguido por clássicos como 'Pais e Filhos', 'Eduardo e Mônica' e 'Que País É Este'. A banda encerrou suas atividades em 1996 após a morte de Renato Russo, mas seu legado permanece vivo, influenciando gerações e sendo referência na música brasileira."
    },
]
