users = [
    {
        "email": 'luansilva250807@gmail.com',
        "password": 'luan2508',
        "is_superuser": True,
        "is_staff": True,
        "is_active": True,
        "is_artist": False,	 
    },
    {
        "email": 'usuariodeteste1@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste2@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste3@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste4@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste5@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste6@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste7@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste8@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste9@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    },
    {
        "email": 'usuariodeteste10@teste.com',
        "password": 'teste123',
        "is_superuser": False,
        "is_staff": False,
        "is_active": False,
        "is_artist": True,	 
    }
]