# Generated by Django 5.0.7 on 2024-10-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0002_favorite_historicalhistory_history_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='country',
        ),
    ]
