# Generated by Django 5.1.2 on 2024-11-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityposts',
            name='songs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mooner.song'),
        ),
    ]
