# Generated by Django 5.0.7 on 2024-10-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0002_album_date_realized'),
        ('usuario', '0002_alter_usuario_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albuns', to='usuario.artist'),
        ),
    ]
