# Generated by Django 5.1.2 on 2024-11-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0003_alter_album_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
