# Generated by Django 5.0.7 on 2024-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0003_alter_album_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='mooner.song'),
        ),
    ]
