# Generated by Django 5.1.2 on 2024-12-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0004_communityposts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='country',
        ),
        migrations.RemoveField(
            model_name='community',
            name='genre',
        ),
    ]
