# Generated by Django 5.1.2 on 2024-12-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0005_remove_community_country_remove_community_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityposts',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='communityposts',
            name='title',
        ),
    ]
