# Generated by Django 5.0.7 on 2024-10-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0005_alter_history_song_alter_history_usuario_favorite'),
        ('mooner', '0005_playlist'),
    ]

    operations = [
    ]
