# Generated by Django 5.0.7 on 2024-10-18 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0006_merge_20241018_0111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='producer',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='owners',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AddField(
            model_name='playlist',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
