# Generated by Django 5.1.2 on 2024-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0006_remove_communityposts_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='background_dark_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
        migrations.AddField(
            model_name='album',
            name='background_light_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
        migrations.AddField(
            model_name='playlist',
            name='background_dark_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
        migrations.AddField(
            model_name='playlist',
            name='background_light_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
        migrations.AddField(
            model_name='song',
            name='background_dark_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
        migrations.AddField(
            model_name='song',
            name='background_light_color',
            field=models.CharField(max_length=7, null='#000000'),
            preserve_default='#000000',
        ),
    ]
