# Generated by Django 5.1.2 on 2024-12-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0008_communityusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityusers',
            name='artist',
        ),
        migrations.AddField(
            model_name='communityusers',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mooner.community'),
        ),
    ]
