# Generated by Django 5.1.2 on 2024-12-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0009_remove_communityusers_artist_and_more'),
        ('usuario', '0005_remove_artist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.artist'),
        ),
    ]
