# Generated by Django 5.1.2 on 2024-12-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0010_alter_community_autor'),
        ('usuario', '0005_remove_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityposts',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='communityposts',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.artist'),
        ),
    ]
