# Generated by Django 5.1.4 on 2024-12-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0011_communityposts_dislikes_alter_communityposts_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityposts',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mooner.community'),
        ),
    ]
