# Generated by Django 5.0.7 on 2024-09-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_realized', models.DateField(auto_now_add=True)),
                ('uploaded_on', models.DateField(auto_now=True)),
                ('duration', models.DurationField()),
                ('reproductions', models.IntegerField(default=0)),
                ('lyrics', models.TextField()),
                ('cover', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.document')),
            ],
        ),
    ]
