# Generated by Django 5.0.7 on 2024-09-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooner', '0003_lunaai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunaai',
            name='response',
        ),
    ]
