# Generated by Django 5.0.7 on 2024-10-29 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_document_attachment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment_key',
            field=models.UUIDField(default=uuid.uuid4, help_text='Used to attach the document to another object. Cannot be used to retrieve the document file.', unique=True),
        ),
    ]
