# Generated by Django 5.1.2 on 2024-11-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_rename_url_document_secure_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='secure_url',
            new_name='url',
        ),
    ]
