# Generated by Django 5.0.7 on 2024-09-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='DDD',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telephone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
