# Generated by Django 5.0.7 on 2024-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_ddd_usuario_about_usuario_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DDD',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
