# Generated by Django 5.0.7 on 2024-09-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
