# Generated by Django 5.0.7 on 2024-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='premium',
            field=models.CharField(blank=True, choices=[('Eclipse', 'Eclipse'), ('Lua Nova', 'Lua Nova'), ('Apollo 8', 'Apollo 8'), ('Ano Lunar', 'Ano Lunar'), ('Apollo 11', 'Apollo 11')], default=None, max_length=50, null=True),
        ),
    ]
