# Generated by Django 5.1.2 on 2024-11-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
