# Generated by Django 5.0.7 on 2024-10-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='passage_id',
        ),
    ]
