# Generated by Django 5.0.7 on 2024-10-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='DDD',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telephone',
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDD', models.CharField(max_length=5)),
                ('telephone', models.CharField(max_length=11)),
                ('identity', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
