# Generated by Django 5.0.7 on 2024-10-18 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('usuario', '0003_remove_usuario_ddd_remove_usuario_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_artist',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_producer',
        ),
        migrations.AddField(
            model_name='usuario',
            name='DDD',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='folowing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.image'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='type_user',
            field=models.CharField(choices=[('normaluser', 'NormalUser'), ('produtor', 'Produtor'), ('artista', 'Artista')], default='NormalUser', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
