# Generated by Django 5.1.2 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_background_dark_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
