# Generated by Django 5.0.7 on 2024-10-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_is_artist_remove_usuario_is_producer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='DDD',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='about',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='folowing',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='type_user',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='youtube',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_artist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
