# Generated by Django 5.1.2 on 2024-12-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_artist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='description',
        ),
    ]
