# Generated by Django 5.0.7 on 2024-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_ddd_remove_usuario_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
